CREATE OR REPLACE PROCEDURE LeapYear(y IN number)
IS

BEGIN

	IF ( (MOD(y,4)=0) AND ( (MOD(y,100)<>0) OR (MOD(y,400)=0) ) )
	THEN
		DBMS_OUTPUT.PUT_LINE('LEAP YEAR');
	ELSE
		DBMS_OUTPUT.PUT_LINE('NOT A LEAP YEAR');
	END IF;

END;
/