DECLARE 
	num number:=&num;
	temp varchar2(10);
	x number;

BEGIN

	SELECT TO_CHAR(num) INTO temp FROM DUAL;	
	
	FOR i in 1..length(temp)
	LOOP

		SELECT TO_NUMBER(SUBSTR(temp,i,1)) INTO x FROM DUAL;
		
		CASE x
				WHEN 0 THEN DBMS_OUTPUT.PUT_LINE('ZERO ');
				WHEN 1 THEN DBMS_OUTPUT.PUT_LINE('ONE ');
				WHEN 2 THEN DBMS_OUTPUT.PUT_LINE('TWO ');
				WHEN 3 THEN DBMS_OUTPUT.PUT_LINE('THREE ');
				WHEN 4 THEN DBMS_OUTPUT.PUT_LINE('FOUR ');
				WHEN 5 THEN DBMS_OUTPUT.PUT_LINE('FIVE ');
				WHEN 6 THEN DBMS_OUTPUT.PUT_LINE('SIX ');
				WHEN 7 THEN DBMS_OUTPUT.PUT_LINE('SEVEN ');
				WHEN 8 THEN DBMS_OUTPUT.PUT_LINE('EIGHT ');
				WHEN 9 THEN DBMS_OUTPUT.PUT_LINE('NINE ');

		END CASE;

	END LOOP;


END;
/